import exampleimg1 from "@/assets/yacht-images/image1.jpg";
import exampleimg2 from "@/assets/yacht-images/image2.jpg";
import exampleimg3 from "@/assets/yacht-images/image3.jpg";
import exampleimg4 from "@/assets/yacht-images/image4.jpg";
import exampleimg5 from "@/assets/yacht-images/image5.jpg";



import centerConsoleImg from "@/assets/popular-categories/center-console.png";
import sportfishImg from "@/assets/popular-categories/sportfish.png";
import luxuryYachtsImg from "@/assets/popular-categories/luxury-yachts.png";
import catamaransImg from "@/assets/popular-categories/catamarans.png";
import cruisersImg from "@/assets/popular-categories/cruisers.png";
import whyImg1 from "@/assets/local-marketplace/img1.jpg";
import whyImg2 from "@/assets/local-marketplace/img2.png";
import whyImg3 from "@/assets/local-marketplace/img3.png";

export const demodata = [
  {
    brand_make: "Viking",
    model: "80 Enclosed Skybridge",
    built_year: 2018,
    length: "80 ft",
    number_of_engine: 2,
    class: "Flybridge",
    material: "Fiberglass",
    number_of_cabin: 2,
    number_of_heads: 5,
    beam_size: "21 ft 4 in",
    fuel_type: "Diesel",
    max_draft: "5 ft 7 in",
    name: "ON THE EDGE",
    location: "Montauk, NY",
    condition: "Used",
    price: 6250000,
    images: [exampleimg1, exampleimg2, exampleimg3, exampleimg4, exampleimg5],
    image: exampleimg1,
  },
  {
    brand_make: "Sunseeker",
    model: "76 Yacht",
    built_year: 2020,
    length: "76 ft",
    number_of_engine: 2,
    class: "Motor Yacht",
    material: "Fiberglass",
    number_of_cabin: 4,
    number_of_heads: 4,
    beam_size: "18 ft 9 in",
    fuel_type: "Diesel",
    max_draft: "5 ft 3 in",
    name: "AZURE DREAM",
    location: "Miami, FL",
    condition: "Used",
    price: 4850000,
    images: [exampleimg2, exampleimg3, exampleimg4, exampleimg5, exampleimg1],
    image: exampleimg2,
  },
  {
    brand_make: "Azimut",
    model: "Grande 95RPH",
    built_year: 2019,
    length: "95 ft",
    number_of_engine: 2,
    class: "Flybridge",
    material: "Fiberglass",
    number_of_cabin: 5,
    number_of_heads: 6,
    beam_size: "23 ft 2 in",
    fuel_type: "Diesel",
    max_draft: "6 ft 8 in",
    name: "BELLA VITA",
    location: "Fort Lauderdale, FL",
    condition: "Used",
    price: 8900000,
    images: [exampleimg3, exampleimg4, exampleimg5, exampleimg1, exampleimg2],
    image: exampleimg3,
  },
  {
    brand_make: "Princess",
    model: "88 Motor Yacht",
    built_year: 2021,
    length: "88 ft",
    number_of_engine: 2,
    class: "Motor Yacht",
    material: "Fiberglass",
    number_of_cabin: 4,
    number_of_heads: 5,
    beam_size: "21 ft 8 in",
    fuel_type: "Diesel",
    max_draft: "6 ft 2 in",
    name: "SERENITY NOW",
    location: "Newport, RI",
    condition: "Used",
    price: 7500000,
    images: [exampleimg4, exampleimg5, exampleimg1, exampleimg2, exampleimg3],
    image: exampleimg4,
  },
  {
    brand_make: "Ferretti",
    model: "720 Flybridge",
    built_year: 2017,
    length: "72 ft",
    number_of_engine: 2,
    class: "Flybridge",
    material: "Fiberglass",
    number_of_cabin: 3,
    number_of_heads: 3,
    beam_size: "19 ft 6 in",
    fuel_type: "Diesel",
    max_draft: "5 ft 9 in",
    name: "OCEAN BREEZE",
    location: "San Diego, CA",
    condition: "Used",
    price: 3750000,
    images: [exampleimg5, exampleimg1, exampleimg2, exampleimg3, exampleimg4],
    image: exampleimg5,
  },
  {
    brand_make: "Hatteras",
    model: "M90 Panacera",
    built_year: 2022,
    length: "90 ft",
    number_of_engine: 2,
    class: "Motor Yacht",
    material: "Fiberglass",
    number_of_cabin: 4,
    number_of_heads: 5,
    beam_size: "23 ft 11 in",
    fuel_type: "Diesel",
    max_draft: "6 ft 5 in",
    name: "TRANQUILITY",
    location: "Charleston, SC",
    condition: "Used",
    price: 9200000,
    images: [exampleimg1, exampleimg3, exampleimg5, exampleimg2, exampleimg4],
    image: exampleimg1,
  },
  {
    brand_make: "Pershing",
    model: "82 VHP",
    built_year: 2019,
    length: "82 ft",
    number_of_engine: 3,
    class: "Sport Yacht",
    material: "Fiberglass",
    number_of_cabin: 3,
    number_of_heads: 3,
    beam_size: "19 ft 4 in",
    fuel_type: "Diesel",
    max_draft: "5 ft 11 in",
    name: "VELOCITY",
    location: "West Palm Beach, FL",
    condition: "Used",
    price: 5900000,
    images: [exampleimg2, exampleimg4, exampleimg1, exampleimg5, exampleimg3],
    image: exampleimg2,
  },
  {
    brand_make: "Maritimo",
    model: "X60 Flybridge",
    built_year: 2020,
    length: "60 ft",
    number_of_engine: 2,
    class: "Flybridge",
    material: "Fiberglass",
    number_of_cabin: 3,
    number_of_heads: 2,
    beam_size: "17 ft 3 in",
    fuel_type: "Diesel",
    max_draft: "4 ft 10 in",
    name: "SOUTHERN CROSS",
    location: "Seattle, WA",
    condition: "Used",
    price: 2850000,
    images: [exampleimg3, exampleimg5, exampleimg2, exampleimg4, exampleimg1],
    image: exampleimg3,
  },
  {
    brand_make: "Benetti",
    model: "Delfino 95",
    built_year: 2018,
    length: "95 ft",
    number_of_engine: 2,
    class: "Motor Yacht",
    material: "Fiberglass",
    number_of_cabin: 5,
    number_of_heads: 6,
    beam_size: "22 ft 7 in",
    fuel_type: "Diesel",
    max_draft: "6 ft 9 in",
    name: "MIDNIGHT SUN",
    location: "Naples, FL",
    condition: "Used",
    price: 10500000,
    images: [exampleimg4, exampleimg2, exampleimg5, exampleimg1, exampleimg3],
    image: exampleimg4,
  },
  {
    brand_make: "Tiara",
    model: "53 Flybridge",
    built_year: 2021,
    length: "53 ft",
    number_of_engine: 2,
    class: "Flybridge",
    material: "Fiberglass",
    number_of_cabin: 2,
    number_of_heads: 2,
    beam_size: "16 ft 2 in",
    fuel_type: "Diesel",
    max_draft: "4 ft 6 in",
    name: "ISLAND TIME",
    location: "Annapolis, MD",
    condition: "Used",
    price: 1950000,
    images: [exampleimg5, exampleimg3, exampleimg4, exampleimg2, exampleimg1],
    image: exampleimg5,
  },
];

export const democategoriesdata = [
  {
    id: 1,
    name: "Center Consoles",
    image: centerConsoleImg,
  },
  {
    id: 2,
    name: "SportFish",
    image: sportfishImg,
  },
  {
    id: 3,
    name: "Luxury Yachts ",
    image: luxuryYachtsImg,
  },
  {
    id: 4,
    name: "Catamarans",
    image: catamaransImg,
  },
  {
    id: 5,
    name: "Cruisers",
    image: cruisersImg,
  },
];

export const whyUsData = {
  label: 'Why us?',
  heading: "Florida's #1 Local Yacht Marketplace",
  description:
    "FloridaYachtTrader.com makes it easy for buyers and sellers to connect in one trusted place. From center consoles to luxury yachts, we're the go-to marketplace built for Florida boaters. With powerful search tools, premium listings, and local expertise, finding your dream yacht has never been simpler.",
  stats: [
    { value: '24+ Years', label: 'Yachting Excellence' },
    { value: '2000+', label: 'Boats Sold Per Year' },
    { value: '1000+', label: 'Listings viewed monthly' },
  ],
  cta: 'List Your Boat For Sale',
  images: [whyImg1, whyImg2, whyImg3],
};
